# Generated by Django 3.2.6 on 2021-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('news', 'News'), ('activities', 'Activities'), ('projects', 'Projects'), ('internships', 'Internships')], default='news', max_length=15),
        ),
    ]
