# Generated by Django 3.2.3 on 2021-08-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mg_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('age', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='static/default/profile_pic.png', upload_to='profile_pic')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mg_auth.mg_user')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
