# Generated by Django 3.2.3 on 2021-08-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='article_img')),
                ('description', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('news', 'News'), ('activities', 'Activities'), ('school_projects', 'School Projects'), ('international_internships', 'International Internships')], default='news', max_length=25)),
            ],
        ),
    ]
